// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../scripts/app.js', ['tasks.App'], ['tasks.Tasks']);
goog.addDependency('../../../scripts/tasks.js', ['tasks.Tasks'], ['goog.ui.Component']);
