// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../scripts/app.js', ['tasks.App'], ['goog.dom', 'tasks.Tasks']);
goog.addDependency('../../../scripts/soyutils_usegoog.js', ['soy', 'soy.StringBuilder', 'soy.esc', 'soydata', 'soydata.SanitizedHtml', 'soydata.SanitizedHtmlAttribute', 'soydata.SanitizedJsStrChars', 'soydata.SanitizedUri'], ['goog.asserts', 'goog.dom.DomHelper', 'goog.format', 'goog.i18n.BidiFormatter', 'goog.i18n.bidi', 'goog.soy', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency('../../../scripts/tasks.js', ['tasks.Tasks'], ['goog.soy', 'goog.ui.Component', 'tasks.tasks_template']);
goog.addDependency('../../../scripts/tasks_template.js', ['tasks.tasks_template'], ['soy', 'soy.StringBuilder']);
